name: Cypress not full reports tests

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Select the environment
        options:
        - dev
        - staging
        - prod
        required: true
        default: staging
jobs:
  Not-full-reports-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.5.0-chrome97-ff96
    strategy:
      fail-fast: false
      matrix:
        containers: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run not snapshot tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          browser: chrome
          spec: cypress/integration/not_full_reports/**
          tag: ${{github.event.inputs.env}}
          parallel: true
        env:
          CYPRESS_USERNAME: ${{ secrets.USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.TEST_LAUNCHES_RECORD_KEY }}
          CYPRESS_url: ${{ github.event.inputs.env }}
          СYPRESS_grepTags: -@snapshot_tests
          CYPRESS_grepFilterSpecs: true
      - name: Cypress run snapshot tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          browser: chrome
          spec: cypress/integration/not_full_reports/**
          tag: ${{ github.event.inputs.env }}
          parallel: true
          headless: true
        env:
          CYPRESS_USERNAME: ${{ secrets.USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.TEST_LAUNCHES_RECORD_KEY }}
          CYPRESS_url: ${{ github.event.inputs.env }}
          СYPRESS_grepTags: @snapshot_tests
          CYPRESS_grepFilterSpecs: true
